
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\x84"\xeb \xdb\xa46\xc9\x92e4=\xd79\x85l'

_lr_action_items = {'MUL_OP':([1,2,5,6,],[3,-1,-3,3,]),'$end':([1,2,5,6,],[0,-1,-3,-2,]),'NUMBER':([0,3,4,],[2,2,2,]),'ADD_OP':([1,2,5,6,],[4,-1,-3,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,],[1,5,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('expression',1,'p_expression_num','U:\\3\xe8me\\Langage et compilateur\\interpreteur\\analys.py',13),
  ('expression',3,'p_expression_op','U:\\3\xe8me\\Langage et compilateur\\interpreteur\\analys.py',17),
  ('expression',3,'p_expression_op','U:\\3\xe8me\\Langage et compilateur\\interpreteur\\analys.py',18),
]
